stages:
  - lint
  - build
  - test
  - deploy

variables:
  NODE_ENV: 'test'
  CI: 'true'

image: node:14

cache:
  paths:
    - node_modules/

before_script:
  - npm cache clean --force
  - npm install

lint:
  stage: lint
  before_script:
  - cd api
  script:
    - npm run lint
  allow_failure: true
  artifacts:
    reports:
      junit: reports/lint-report.xml
    paths:
      - reports/

build:
  stage: build
  before_script:
  - cd api
  script:
    - npm run build
    - ls -l reports/
  artifacts:
    paths:
      - reports/

install_dependencies:
  stage: .pre
  script:
    - npm ci

test:
  stage: test
  before_script:
  - cd api
  script:
    - npm run test -- --coverage --watchAll=false
  artifacts:
    reports:
      junit: reports/test-report.xml
    paths:
      - coverage
  coverage: '/All files[^|]*\|[^|]*\|[^|]*\|[^|]*\|([^|]*)%/'

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
  only:
    - testing_test