image: node:latest

stages:
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: .pre
  script:
    - npm ci

test:
  stage: test
  script:
    - cd api
    - npm run test -- --coverage --watchAll=false
  artifacts:
    reports:
      junit: api/reports/test-report.xml
      cobertura: api/coverage/cobertura-coverage.xml