image: node:latest

stages:
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: .pre
  script:
    - npm ci

test:
  stage: test
  script: npm test
  artifacts:
    reports:
      coverage_format: cobertura
      junit: test-results/junit/results.xml