version: '3.8'
services:
  nginx:
    image: nginx:latest
    stdin_open: true
    expose:
      - "8080"
    ports:
      - "8080:80"
    volumes:
      - ./admin-panel/nginx.conf:/etc/nginx/nginx.conf
      - ./admin-panel/build:/var/www/html
    depends_on:
      - api
      - admin-panel

  api:
    build: ./api
    container_name: api_backend
    ports:
      - '3001:3001'
    volumes:
      - ./api:/app
    restart: unless-stopped

  admin-panel:
    build: ./admin-panel
    container_name: admin-panel
    volumes:
      - ./admin-panel/build:/var/www/html
    stdin_open: true
    tty: true
    restart: unless-stopped
